- name: playbook finished
  hosts: localhost
  vars:
    readme_file: "/home/ansible/AnsibleRun_{{ ansible_facts.fqdn }}_{{ ansible_date_time.date }}.txt"
  tasks:
  - name: set playbook end date
    command: date
    register: stop_date

  - name: add Succesful Finish message
    shell: echo "{{ item }}" >> "{{ readme_file }}"
    loop:
    - "The playbook finished successfuly at {{ stop_date.stdout_lines }}"

  - name: copy the file to client
    copy:
      src: "{{ readme_file }}"
      dest: "{{ readme_file }}"
    delegate_to: "{{ item }}"
    loop: "{{ groups.ora }}"
